---
collections:
  - name: ansible.netcommon
    version: "==8.2.0"
  - name: ansible.posix
    version: "==2.1.0"
  - name: ansible.utils
    version: "==6.0.0"
  - name: ansible.windows
    version: "==3.3.0"
  - name: arubanetworks.aos_switch
    version: "==1.7.0"
  - name: arubanetworks.aoscx
    version: "==4.4.0"
  - name: arubanetworks.aruba_central
    version: "==1.0.3"
  - name: cloud.common
    version: "==5.0.0"
  - name: community.general
    version: "==12.2.0"
  - name: community.vmware
    version: "==6.1.0"
  - name: community.windows
    version: "==3.1.0"
  - name: vmware.vmware_rest
    version: "==4.9.0"
  - name: zabbix.zabbix
    version: "==1.4.2"
  - name: dellemc.os6
    version: "==1.0.7"